use warnings;
use strict;
use utf8;
use FindBin '$Bin';
use Test::More;
my $builder = Test::More->builder;
binmode $builder->output,         ":utf8";
binmode $builder->failure_output, ":utf8";
binmode $builder->todo_output,    ":utf8";
binmode STDOUT, ":encoding(utf8)";
binmode STDERR, ":encoding(utf8)";
use Image::Similar 'load_image';
use Imager;
my $file = "$Bin/../t/images/chess/chess-300.png";
my $img = Imager->new ();
$img->read (file => $file);
my $is = load_image ($img);
$is->fill_grid ();
$is->write_png ("$Bin/chess-300.png");
done_testing ();
